### ISSUE TITLE
Nanoc 4 video embeds?

### ISSUE THREAD

**Issue by jm3** [stormz/nanoc-plugins#1]
Is it worth trying to make this plugin work on (current) Nanoc 4?

What is the syntax for usage, the Readme doesn't specify.

**Comment by francois2metz** [comment]
It should works. Would be happy to have some feedback. The readme for the embed plugin is here https://github.com/stormz/nanoc-plugins/tree/master/embed

**Comment by jm3** [comment]
Sure, but when i asked, "what's the syntax for usage?", I meant: what's the syntax for using `nanoc-embed` within a page? e.g. how do I format the youtube URL in erb / haml / whatever? should i wrap it in [angle brackets] or something?

**Comment by francois2metz** [comment]
Just put any youtube URL in your page. Like https://www.youtube.com/watch?v=MJL0ANWcxZM

**Comment by jm3** [comment]
oh wow, it totally works! duh, thank you! that's awesome :)
